/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MDMakerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
async function populateFolderDropdown(app, dropdown, currentValue, onChange) {
  dropdown.addOption("/", "\u30EB\u30FC\u30C8 (/)");
  let folders = app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((f) => f).sort((a, b) => a.path.localeCompare(b.path));
  if (!folders.length) {
    const recurse = async (path) => {
      const result = [];
      try {
        const { folders: subFolders } = await app.vault.adapter.list(path);
        for (const subPath of subFolders) {
          const folder = app.vault.getAbstractFileByPath(subPath);
          if (folder instanceof import_obsidian.TFolder) {
            result.push(folder);
            result.push(...await recurse(subPath));
          }
        }
      } catch (error) {
      }
      return result;
    };
    folders = await recurse("/");
  }
  folders.forEach((folder) => {
    if (folder.path !== "/") {
      dropdown.addOption(folder.path, folder.path);
    }
  });
  dropdown.setValue(currentValue);
  dropdown.onChange(onChange);
}
var DEFAULT_SETTINGS = {
  defaultFileCount: 5,
  defaultBaseName: "\u30D5\u30A1\u30A4\u30EB",
  targetFolder: "/",
  numberFormat: "\uFF08n\uFF09",
  // デフォルトは全角括弧＋n
  padWidth: 2
};
var MDMakerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("file-plus", "MD Maker", () => {
      new MDMakerModal(this.app, this).open();
    });
    this.addCommand({
      id: "open-mdmaker-modal",
      name: "MD Maker\u3092\u958B\u304F",
      callback: () => new MDMakerModal(this.app, this).open()
    });
    this.addSettingTab(new MDMakerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 全角数字を半角数字に変換する
   */
  convertFullwidthToHalfwidth(text) {
    const fullwidthDigits = "\uFF10\uFF11\uFF12\uFF13\uFF14\uFF15\uFF16\uFF17\uFF18\uFF19";
    const halfwidthDigits = "0123456789";
    return text.replace(/[０-９]/g, (char) => halfwidthDigits[fullwidthDigits.indexOf(char)]);
  }
  /**
   * 連番フォーマットの変換処理
   * rawFmt 中のすべての "n" を連番に置換し、
   * "\n"（バックスラッシュ＋n）だけはリテラル "n" として扱います。
   */
  formatSegment(rawFormat, padWidth, index) {
    const ESCAPE_MARKER = "__LITERAL_N__";
    let text = rawFormat.replace(/\\n/g, ESCAPE_MARKER);
    const numberString = padWidth > 0 ? index.toString().padStart(padWidth, "0") : index.toString();
    text = text.replace(/n/g, numberString);
    return text.replace(new RegExp(ESCAPE_MARKER, "g"), "n");
  }
  /**
   * 複数のMarkdownファイルを作成する
   */
  async createFiles(folder, baseName, count, numberFormat, padWidth) {
    const rawFormat = numberFormat || this.settings.numberFormat;
    const padding = padWidth !== void 0 ? padWidth : this.settings.padWidth;
    const created = [];
    const failed = [];
    for (let i = 1; i <= count; i++) {
      const segment = this.formatSegment(rawFormat, padding, i);
      const fileName = `${baseName}${segment}.md`;
      const filePath = folder.path === "/" ? fileName : `${folder.path}/${fileName}`;
      try {
        if (this.app.vault.getAbstractFileByPath(filePath)) {
          failed.push(`${fileName} (\u65E2\u306B\u5B58\u5728)`);
          continue;
        }
        await this.app.vault.create(filePath, "");
        created.push(fileName);
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : "Unknown error";
        failed.push(`${fileName} (\u30A8\u30E9\u30FC: ${errorMessage})`);
      }
    }
    return { created, failed };
  }
};
var MDMakerModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.baseName = plugin.settings.defaultBaseName;
    this.fileCount = plugin.settings.defaultFileCount;
    this.numberFormat = plugin.settings.numberFormat;
    this.padWidth = plugin.settings.padWidth;
    const path = plugin.settings.targetFolder || "/";
    const af = this.app.vault.getAbstractFileByPath(path);
    this.selectedFolder = af instanceof import_obsidian.TFolder ? af : this.app.vault.getRoot();
  }
  onOpen() {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "MD Maker - \u8907\u6570\u30D5\u30A1\u30A4\u30EB\u4F5C\u6210" });
    new import_obsidian.Setting(this.contentEl).setName("\u4F5C\u6210\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u30D5\u30A1\u30A4\u30EB\u3092\u4F5C\u6210\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044").addDropdown((dropdown) => {
      populateFolderDropdown(
        this.app,
        dropdown,
        this.selectedFolder.path,
        (value) => {
          const folder = this.app.vault.getAbstractFileByPath(value);
          this.selectedFolder = folder instanceof import_obsidian.TFolder ? folder : this.app.vault.getRoot();
        }
      );
    });
    new import_obsidian.Setting(this.contentEl).setName("\u30D9\u30FC\u30B9\u540D").setDesc("\u30D5\u30A1\u30A4\u30EB\u540D\u306E\u30D9\u30FC\u30B9\u3092\u5165\u529B").addText((textInput) => {
      textInput.setPlaceholder("\u4F8B: \u30E1\u30E2").setValue(this.baseName).onChange((value) => {
        this.baseName = value;
      });
    });
    new import_obsidian.Setting(this.contentEl).setName("\u30D5\u30A1\u30A4\u30EB\u6570").setDesc("1\u301C100 \u306E\u7BC4\u56F2\u3067\u5165\u529B").addText((textInput) => {
      textInput.setPlaceholder("\u4F8B: 5").setValue(this.fileCount.toString()).onChange((value) => {
        const convertedValue = this.plugin.convertFullwidthToHalfwidth(value);
        const numericValue = parseInt(convertedValue);
        if (!isNaN(numericValue) && numericValue >= 1 && numericValue <= 100) {
          this.fileCount = numericValue;
        }
      });
    });
    new import_obsidian.Setting(this.contentEl).setName("\u9023\u756A\u5F62\u5F0F").setDesc("`n` \u306F\u5FC5\u305A\u756A\u53F7\u306B\u3002`\\n` \u3067\u30EA\u30C6\u30E9\u30EB\u300Cn\u300D\u3092\u51FA\u529B").addText((textInput) => {
      textInput.setPlaceholder(DEFAULT_SETTINGS.numberFormat).setValue(this.numberFormat).onChange((value) => {
        this.numberFormat = value;
      });
    });
    new import_obsidian.Setting(this.contentEl).setName("\u30BC\u30ED\u30D1\u30C7\u30A3\u30F3\u30B0\u6841\u6570").setDesc("\u9023\u756A\u3092\u4F55\u6841\u3067\u30BC\u30ED\u30D1\u30C7\u30A3\u30F3\u30B0\u3059\u308B\u304B\uFF080\u306F\u306A\u3057\uFF09").addDropdown((dropdown) => {
      ["0", "2", "3"].forEach((value) => {
        dropdown.addOption(value, value === "0" ? "\u306A\u3057" : `${value}\u6841`);
      });
      dropdown.setValue(String(this.padWidth));
      dropdown.onChange((value) => {
        this.padWidth = parseInt(value);
      });
    });
    const preview = this.contentEl.createDiv({ cls: "mdmaker-preview" });
    this.updatePreview(preview);
    this.contentEl.createEl("hr");
    const buttonContainer = this.contentEl.createDiv({ cls: "modal-button-container" });
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "8px";
    const createButton = buttonContainer.createEl("button", {
      text: "\u4E00\u62EC\u4F5C\u6210",
      cls: "mdmaker-create-button"
    });
    createButton.addEventListener("click", async () => {
      await this.executeCreate();
    });
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u30AD\u30E3\u30F3\u30BB\u30EB",
      cls: "mdmaker-cancel-button"
    });
    cancelButton.addEventListener("click", () => this.close());
    this.contentEl.addEventListener("input", () => this.updatePreview(preview));
  }
  updatePreview(container) {
    container.empty();
    if (!this.baseName.trim() || this.fileCount < 1)
      return;
    const maxPreviewCount = Math.min(this.fileCount, 5);
    for (let i = 1; i <= maxPreviewCount; i++) {
      const segment = this.plugin.formatSegment(this.numberFormat, this.padWidth, i);
      const item = container.createDiv({ cls: "mdmaker-preview-item" });
      item.textContent = `${this.baseName}${segment}.md`;
    }
    if (this.fileCount > 5) {
      const moreItem = container.createDiv({ cls: "mdmaker-preview-item" });
      moreItem.style.fontStyle = "italic";
      moreItem.textContent = `...\u3042\u3068${this.fileCount - 5}\u500B`;
    }
  }
  async executeCreate() {
    if (!this.baseName.trim()) {
      new import_obsidian.Notice("\u30D9\u30FC\u30B9\u540D\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044");
      return;
    }
    if (this.fileCount < 1 || this.fileCount > 100) {
      new import_obsidian.Notice("\u30D5\u30A1\u30A4\u30EB\u6570\u3092\u6B63\u3057\u304F\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044");
      return;
    }
    try {
      this.plugin.settings.numberFormat = this.numberFormat;
      this.plugin.settings.padWidth = this.padWidth;
      await this.plugin.saveSettings();
      const { created, failed } = await this.plugin.createFiles(
        this.selectedFolder,
        this.baseName.trim(),
        this.fileCount,
        this.numberFormat,
        this.padWidth
      );
      if (created.length) {
        new import_obsidian.Notice(`${created.length}\u500B\u306E\u30D5\u30A1\u30A4\u30EB\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F`);
      }
      if (failed.length) {
        new import_obsidian.Notice(`${failed.length}\u500B\u306E\u30D5\u30A1\u30A4\u30EB\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F`);
      }
      this.close();
    } catch (error) {
      new import_obsidian.Notice("\u30D5\u30A1\u30A4\u30EB\u4F5C\u6210\u4E2D\u306B\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MDMakerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl("h2", { text: "MD Maker \u8A2D\u5B9A" });
    new import_obsidian.Setting(this.containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u30D5\u30A1\u30A4\u30EB\u540D").setDesc("\u65B0\u898F\u30D5\u30A1\u30A4\u30EB\u306E\u30D9\u30FC\u30B9\u30CD\u30FC\u30E0").addText((textInput) => {
      textInput.setPlaceholder(DEFAULT_SETTINGS.defaultBaseName).setValue(this.plugin.settings.defaultBaseName).onChange(async (value) => {
        this.plugin.settings.defaultBaseName = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(this.containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u30D5\u30A1\u30A4\u30EB\u6570").setDesc("1\u301C100\u306E\u7BC4\u56F2").addText((textInput) => {
      textInput.setPlaceholder(String(DEFAULT_SETTINGS.defaultFileCount)).setValue(String(this.plugin.settings.defaultFileCount)).onChange(async (value) => {
        const numericValue = parseInt(value);
        if (!isNaN(numericValue) && numericValue >= 1 && numericValue <= 100) {
          this.plugin.settings.defaultFileCount = numericValue;
          await this.plugin.saveSettings();
        }
      });
    });
    new import_obsidian.Setting(this.containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u9023\u756A\u5F62\u5F0F").setDesc("`n` \u306F\u9023\u756A\u306B\u3002`\\n` \u3067\u6587\u5B57n\u3068\u3057\u3066\u51FA\u529B").addText((textInput) => {
      textInput.setPlaceholder(DEFAULT_SETTINGS.numberFormat).setValue(this.plugin.settings.numberFormat).onChange(async (value) => {
        this.plugin.settings.numberFormat = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(this.containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u30BC\u30ED\u30D1\u30C7\u30A3\u30F3\u30B0\u6841\u6570").setDesc("\u9023\u756A\u3092\u4F55\u6841\u3067\u30BC\u30ED\u30D1\u30C7\u30A3\u30F3\u30B0\u3059\u308B\u304B\uFF080\u306F\u306A\u3057\uFF09").addDropdown((dropdown) => {
      ["0", "2", "3"].forEach((value) => {
        dropdown.addOption(value, value === "0" ? "\u306A\u3057" : `${value}\u6841`);
      });
      dropdown.setValue(String(this.plugin.settings.padWidth));
      dropdown.onChange(async (value) => {
        this.plugin.settings.padWidth = parseInt(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(this.containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u4F5C\u6210\u5148\u30C7\u30A3\u30EC\u30AF\u30C8\u30EA").setDesc("\u5BFE\u8C61\u30C7\u30A3\u30EC\u30AF\u30C8\u30EA\u306B\u30D5\u30A1\u30A4\u30EB\u304C\u4E00\u62EC\u4F5C\u6210\u3055\u308C\u307E\u3059\u3002").addDropdown((dropdown) => {
      populateFolderDropdown(
        this.app,
        dropdown,
        this.plugin.settings.targetFolder,
        async (value) => {
          this.plugin.settings.targetFolder = value;
          await this.plugin.saveSettings();
        }
      );
    });
    const actionContainer = this.containerEl.createDiv();
    actionContainer.style.textAlign = "right";
    actionContainer.style.marginTop = "40px";
    const quickCreateButton = actionContainer.createEl("button", {
      text: "\u8A2D\u5B9A\u5024\u3067\u4E00\u62EC\u4F5C\u6210",
      cls: "mdmaker-create-button-settings"
    });
    quickCreateButton.addEventListener("click", async () => {
      const folderPath = this.plugin.settings.targetFolder || "/";
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      const targetFolder = folder instanceof import_obsidian.TFolder ? folder : this.app.vault.getRoot();
      const { created, failed } = await this.plugin.createFiles(
        targetFolder,
        this.plugin.settings.defaultBaseName,
        this.plugin.settings.defaultFileCount
      );
      if (created.length) {
        new import_obsidian.Notice(`${created.length}\u500B\u306E\u30D5\u30A1\u30A4\u30EB\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F`);
      }
      if (failed.length) {
        new import_obsidian.Notice(`${failed.length}\u500B\u306E\u30D5\u30A1\u30A4\u30EB\u4F5C\u6210\u306B\u5931\u6557\u3057\u307E\u3057\u305F`);
      }
    });
  }
};
